var axios = require('axios');
var FormData = require('form-data');
var fs = require('fs');
var data = new FormData();
data.append('changeLogZip', fs.createReadStream('liquibase.zip'));

var tenant = "1678";
var username = "C5337551";
var pwd = "Sap@12345";

var config = {
  method: "POST",
  url: 'https://tenant.callidusondemand.com/TrueComp-SaaS/services/rest/touchlessdeployment/status',
  auth: {
    username: username,
    password: pwd
  },
  headers: { 
    ...data.getHeaders()
  },
  data: data
};

axios(config)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });
