import requests
import os

tenant = os.environ.get('TENANT')
token = 'Basic ' + os.environ.get('TOKEN')

url = "https://" +tenant+ ".callidusondemand.com/TrueComp-SaaS/services/rest/touchlessdeployment/update?changeMasterFile=master.xml"
print(url)

payload={}
files=[
  ('changeLogZip',('liquibase.zip',open('liquibase.zip','rb'),'application/zip'))
]
headers = {
  'Authorization': token
}
print(headers)
response = requests.request("POST", url, headers=headers, data=payload, files=files)

print(response.text)
